
meta_product_name: "Access Inn Patta"
meta_title: "Boutique hotel, Restaurant & Bar - Pattaya center"
meta_description: "Access inn Pattaya is a boutique hotel located in the vibrant city of Pattaya center."
meta_image: "accessinn-fbcover.png" # should exist in `app/assets/images/`
